const express = require("express");
const swaggerJsDoc = require("swagger-jsdoc");
const swaggerUi = require("swagger-ui-express");
const { version } = require("../../package.json");

const options = {
  definition: {
    openapi: "3.0.0",
    info: {
      title: "🚀 Lab365 Fullstack - Node Express Rest API",
      version: version,
      description: `Server resources documentation generated by <b>Ariel Duarte (c) 2023</b>.
        <a target="_blank" href="https://documenter.getpostman.com/view/3891670/2s93JtPiHN"> POSTMAN Documentation</a>
        `,
    },
  },
  servers: [
    {
      url: "http://localhost:3000/api",
      description: "Development server",
    },
    {
      url: "https://lab-365-fullstack-node-api-production.up.railway.app/api/",
      description: "Production server",
    },
  ],
  apis: ["./src/routes/*.js", "./src/models/*.js"],
};

const swaggerSpec = swaggerJsDoc(options);

const swaggerDocs = (app, port) => {
  // Swagger page
  app.use("/api/docs", swaggerUi.serve);
  app.use("/api/docs", swaggerUi.setup(swaggerSpec));

  // Docs in JSON format
  app.get("/api/docs.json", (req, res) => {
    res.setHeader("Content-Type", "application/json");
    res.send(swaggerSpec);
  });
  console.log(`Docs available at http://localhost:${port}/api/docs`);
};

module.exports = {
  swaggerDocs,
};
